### ISSUE TITLE
If AABh is deactivated, make elevates warn endlessly

### ISSUE THREAD

**Issue by kommandantredundant** [GreyWolfDev/Executrix#60]
If AllAdminsBanhammer is deactivated, make elevates warns exceed the warn limit instead of banning. Could be a single option.

**Comment by Olgabrezel** [comment]
Uhm... why? Elevates can always ban anyway...

**Comment by kommandantredundant** [comment]
OK, maybe I was thinking too much in my idea from #59 which could then include elevates who cannot ban. But either way I would love to see a possibility to have elevates that can't ban and make that admin-exclusive. Else, there is no need to have elevates, as you could just have an admin with less permissions instead.

Maybe close this and add that in #59 as I'm crisscrossing ideas here...

**Comment by Olgabrezel** [comment]
Okay, let's close this and I will answer you in more detail way in #59.
