### ISSUE TITLE
extralist cmd #bug 

### ISSUE THREAD

**Issue by sharnass** [GreyWolfDev/Executrix#74]
one group has a problem with /extralist cmd 
this cmd is not working in their group 
if in settings of the extra list set on sending msg to group > when you use it bot say nothing 
if in settings of the extra list set to send msg in PM > when you use this cmd in group bot says: plz start me in PM first (although you started bot before)
please check this :https://t.me/ExecutrixBot?start=extralist_-1001297442496
group id :-1001297442496

**Comment by Olgabrezel** [comment]
@sharnass They have a total of 627 extras set, the extralist message is way too long to be sent. The main issue is: There should be a limit to the number and trigger-length of extra commands a group can set.
